server.port: 7002

springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_chatting
    username: "username"
    password: "password"
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
token:
  secret-key: "SECRET"
  refresh-secret-key: "REFRESH_SECRET"
  token_time: 300
  refresh-token-time: 300